# only important for github actions in order to create users inside the docker container
python3 manage.py shell -c "
from django.contrib.auth.models import User, Group
from django.contrib.auth.models import Permission
from django.contrib.contenttypes.models import ContentType
from ..models import HistopathologicalSample
ct = ContentType.objects.get_for_model(HistopathologicalSample)
user = User.objects.create_user('test_SPL', password='test4life')
new_group, created = Group.objects.get_or_create(name='SPL')
new_group.user_set.add(user)
permission = Permissions.objects.get_or_create(name='spl_fields', code_name='spl_fields', content_type=ct)
new_group.permissions.add(permission)
user.save()
user = User.objects.create_user('test_Recruiter', password='test4life')
new_group, created = Group.objects.get_or_create(name='Recruiter')
new_group.user_set.add(user)
permission = Permissions.objects.get_or_create(name='recruiter_fields', code_name='recruiter_fields', content_type=ct)
new_group.permissions.add(permission)
user.save()
user = User.objects.create_user('test_LB', password='test4life')
new_group, created = Group.objects.get_or_create(name='LiquidBiopsy')
new_group.user_set.add(user)
permission = Permissions.objects.get_or_create(name='liquidbiopsy_fields', code_name='liquidbiopsy_fields', content_type=ct)
new_group.permissions.add(permission)
user.save()
user = User.objects.create_user('test_ScLab', password='test4life')
new_group, created = Group.objects.get_or_create(name='scOpenLab')
new_group.user_set.add(user)
permission = Permissions.objects.get_or_create(name='scopenlab_fields', code_name='scopenlab_fields', content_type=ct)
new_group.permissions.add(permission)
user.save()
user = User.objects.create_user('test_Omics', password='test4life')
new_group, created = Group.objects.get_or_create(name='OmicsPath')
new_group.user_set.add(user)
permission = Permissions.objects.get_or_create(name='omicspath_fields', code_name='omicspath_fields', content_type=ct)
new_group.permissions.add(permission)
user.save()
user = User.objects.create_user('test_TUM', password='test4life')
new_group, created = Group.objects.get_or_create(name='TUM')
new_group.user_set.add(user)
permission = Permissions.objects.get_or_create(name='tum_fields', code_name='tum_fields', content_type=ct)
new_group.permissions.add(permission)
user.save()
user = User.objects.create_user('test_Spatial', password='test4life')
new_group, created = Group.objects.get_or_create(name='Spatial')
new_group.user_set.add(user)
permission = Permissions.objects.get_or_create(name='spatial_fields', code_name='spatial_fields', content_type=ct)
new_group.permissions.add(permission)
user.save()
"
