# Generated by Selenium IDE
from selenium.webdriver.common.by import By
from backend.gui.selenium.basic_test_functions import BasicTestClass
import os


class TestUpload(BasicTestClass):

    def test_upload_root(self):
        print("root")

        self.login("root", "root")
        self.sat3_sample_code = "S3C-maynz-0-M1-V-R1"
        
        print("upload here")
        self.upload_file("one_record.csv")
        print("not here")
        # download
        self.driver.find_element(By.ID, "all-samples-nav").click()
        self.driver.find_element(
            By.ID, "download-dropdown-button").click()
        self.driver.find_element(
            By.ID, "download-dropdown-button-CSV").click()

    def test_upload_all_groups_except_spatial(self):
        """
        Spatial is excluded here because the sclab user
        already fills in all the spatial fields
        (for they have write permissions on spatial fields)
        """

        self.sat3_sample_code = "S3C-maynz-0-M1-V-R1"

        user_names = ["test_Recruiter", "test_TUM", "test_SPL",
                      "test_ScLab", "test_LB",
                      "test_Omics"]

        for user in user_names:
            print(user)
            self.login(user, "test4life")
            print(user)
            self.upload_file("one_record.csv")
            self.check_upload()
            self.logout()

        self.login("root", "root")

    def test_upload_spatial(self):

        self.sat3_sample_code = "S3C-maynz-0-M1-V-R1"

        user_names = ["test_Recruiter", "test_Spatial"]

        for user in user_names:
            self.login(user, "test4life")
            self.upload_file("one_record.csv")
            self.check_upload()
            self.logout()

        self.login("root", "root")

    def check_upload(self):
        message_container = self.driver.find_elements(
            By.CLASS_NAME, "messages")

        for message in message_container:

            li = message.find_elements(By.TAG_NAME, "li")
            if len(li) != 0:
                print(li[0].text)
                assert (li[0].text == "File upload successful!")

    def upload_file(self, file_name):
        self.driver.find_element(
          By.ID, "id_file").send_keys(
              os.path.abspath(f"./csv-files/{file_name}"))
        self.driver.find_element(By.ID, "end-of-page").click()
        print("CLICKED UPLOAD")
        self.check_upload()
