# Generated by Selenium IDE

from selenium.webdriver.common.by import By

from selenium.webdriver.common.keys import Keys
from selenium.webdriver.support.select import Select
from backend.gui.selenium.basic_test_functions import BasicTestClass
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.support.ui import WebDriverWait


class TestRootCreateRecordViaForm(BasicTestClass):

    def create_test_record(self):

        wait = WebDriverWait(self.driver, 5)

        wait.until(EC.element_to_be_clickable((By.ID, "id_recruiting_site")))

        recruiting_site = self.driver.find_element(By.ID, "id_recruiting_site")
        recruiting_site.find_element(
            By.XPATH, "//option[. = 'Göttingen']").click()

        self.driver.find_element(
            By.ID, "id_patient_identifier").send_keys("TEST1")

        sex = self.driver.find_element(By.ID, "id_sex")
        sex_select = Select(sex)
        sex_select.select_by_value("m")

        self.driver.find_element(By.ID, "id_died").send_keys("2024-05-14")
        self.driver.find_element(By.ID, "id_died").send_keys(Keys.ENTER)

        # SATURN3 Sample Code
        saturn3_sample_code_0 = self.driver.find_element(
            By.ID, "id_saturn3_sample_code_0")
        select_saturn3_sample_code_0 = Select(saturn3_sample_code_0)
        select_saturn3_sample_code_0.select_by_value("S3P")

        # saturn3_sample_code_1 is filled out automatically

        self.driver.find_element(
            By.ID, "id_saturn3_sample_code_2").send_keys("5")

        saturn3_sample_code_3 = self.driver.find_element(
            By.ID, "id_saturn3_sample_code_3")
        select_saturn3_sample_code_3 = Select(saturn3_sample_code_3)
        select_saturn3_sample_code_3.select_by_value("L")

        self.driver.find_element(
            By.ID, "id_saturn3_sample_code_4").send_keys("9")

        saturn3_sample_code_5 = self.driver.find_element(
            By.ID, "id_saturn3_sample_code_5")
        select_saturn3_sample_code_5 = Select(saturn3_sample_code_5)
        select_saturn3_sample_code_5.select_by_value("P")

        saturn3_sample_code_6 = self.driver.find_element(
            By.ID, "id_saturn3_sample_code_6")
        select_saturn3_sample_code_6 = Select(saturn3_sample_code_6)
        select_saturn3_sample_code_6.select_by_value("L")

        self.driver.find_element(
            By.ID, "id_saturn3_sample_code_7").send_keys("1")
        # end of SATURN3 Sample Code

        self.driver.find_element(
            By.ID, "id_sampling_date").send_keys("2024-05-14")
        self.driver.find_element(
            By.ID, "id_sampling_date").send_keys(Keys.ENTER)

        tissue_type = self.driver.find_element(By.ID, "id_tissue_type")
        select_tissue_type = Select(tissue_type)
        select_tissue_type.select_by_value("PBMC")

        type_of_intervention = self.driver.find_element(
            By.ID, "id_type_of_intervention")
        select_type_of_intervention = Select(type_of_intervention)
        select_type_of_intervention.select_by_value("Blood withdrawal")

        localisation = self.driver.find_element(By.ID, "id_localisation")
        select_localisation = Select(localisation)
        select_localisation.select_by_value("Brain")

        corresponding_organoid = self.driver.find_element(
            By.ID, "id_corresponding_organoid")
        select_corresponding_organoid = Select(corresponding_organoid)
        select_corresponding_organoid.select_by_visible_text("No")

        grading = self.driver.find_element(By.ID, "id_grading")
        select_grading = Select(grading)
        select_grading.select_by_value("G2")

        self.driver.find_element(By.ID, "modalButton").click()
        self.driver.find_element(
            By.CSS_SELECTOR, ".modal-footer > .btn-primary").click()

    def delete_test_record(self):
        self.driver.save_screenshot('screenie.png')
        self.driver.find_element(By.ID, "all-samples-nav").click()
        self.driver.find_element(By.ID, "Delete S3P-TEST1-5-L9-P-L1").click()

    def teardown_method(self, method):

        self.delete_test_record()
        self.logout()
        self.driver.close()
        self.driver.quit()

    def test_rootcreaterecordviaformv2(self):
        self.login("root", "root")
        self.driver.implicitly_wait(2)
        self.create_test_record()

        messages = self.driver.find_elements(By.CLASS_NAME, "messages")

        for message in messages:
            errors = message.find_elements(By.TAG_NAME, "li")
            for err in errors:
                print(err.get_attribute("class"))
                print(err.text)
