# Generated by Selenium IDE

from selenium.webdriver.common.by import By
from .record_generator import RecordGenerator
from selenium.webdriver.support.select import Select
from .basic_test_functions import BasicTestClass


class TestAllUserGroupsForm(BasicTestClass):

    def test_all_users_input(self):
        print("start")
        self.recruiter_create()
        print("recruiter done")
        self.tum_input()
        print("tum done")
        self.spl_input()
        print("spl done")
        self.sclab_input()
        print("scLab done")
        self.spatial_input()
        print("saptial done")
        self.lb_input()
        print("lb done")
        self.omics_input()
        print("omics done")
        self.login("root", "root")

    def search_record(self):
        self.driver.find_element(
            By.CSS_SELECTOR,
            "#id_radio_select > div:nth-child(2) > label").click()
        self.driver.find_element(
            By.ID, "id_search_field").send_keys(self.sat3_sample_code)
        self.driver.find_element(By.ID, "search-button").click()

    def recruiter_create(self):
        self.login("test_Recruiter", "test4life")
        self.create_minimal_test_record()
        self.submit_record()
        self.check_submission()
        self.logout()

    def tum_input(self):
        self.login("test_TUM", "test4life")
        self.search_record()
        self.driver.save_screenshot("screenie.png")
        self.driver.find_element(By.ID, "id_tissue_quality").send_keys(
            RecordGenerator.random_integer_from_1_to_5())
        self.driver.find_element(By.ID, "id_tumor_cell_content").send_keys(
            RecordGenerator.random_integer_from_0_to_100())
        self.driver.find_element(By.ID, "id_percent_avital_cells").send_keys(
            RecordGenerator.random_integer_from_0_to_100())
        self.driver.find_element(
            By.ID,
            "id_comment_tumor_cell_content").send_keys(
                RecordGenerator.random_string_of_length(20))
        self.submit_record()
        self.check_submission()
        self.logout()

    def spl_input(self):
        self.login("test_SPL", "test4life")
        self.search_record()
        print("spl record searched")

        self.driver.find_element(
            By.ID,
            "id_spl_received").send_keys(RecordGenerator.random_date())
        print("spl received")
        spl_status = self.driver.find_element(
            By.ID, "id_spl_status")
        select_spl_status = Select(spl_status)
        select_spl_status.select_by_visible_text(
            RecordGenerator.random_spl_status())
        print("spl status")
        spl_sequencing_type = self.driver.find_element(
            By.ID, "id_spl_sequencing_type")
        select_spl_sequencing_type = Select(spl_sequencing_type)
        select_spl_sequencing_type.select_by_visible_text(
            RecordGenerator.random_spl_sequencing())
        print("spl seq")
        self.submit_record()
        print("submitted")
        self.check_submission()
        self.logout()

    def sclab_input(self):
        self.login("test_ScLab", "test4life")
        self.search_record()
        self.driver.find_element(
            By.ID,
            "id_sclab_received").send_keys(RecordGenerator.random_date())

        self.driver.find_element(
            By.ID,
            "id_sclab_extraction_date").send_keys(
                RecordGenerator.random_date())

        self.driver.find_element(
            By.ID,
            "id_sclab_nuclei_yield").send_keys(
                RecordGenerator.random_integer_from_0_to_100())

        self.driver.find_element(
            By.ID,
            "id_sclab_nuclei_size").send_keys(
                RecordGenerator.random_integer_from_0_to_100())

        sclab_status = self.driver.find_element(
            By.ID, "id_sclab_status")
        select_sclab_status = Select(sclab_status)
        select_sclab_status.select_by_visible_text(
            RecordGenerator.random_sclab_status_choice())

        sclab_sequencing_type = self.driver.find_element(
            By.ID, "id_sclab_sequencing_type")
        select_sclab_sequencing_type = Select(sclab_sequencing_type)
        select_sclab_sequencing_type.select_by_visible_text(
            RecordGenerator.random_sclab_sequencing_types())

        sclab_sorting = self.driver.find_element(
            By.ID, "id_sclab_sorting")
        select_corresponding_organoid = Select(sclab_sorting)
        select_corresponding_organoid.select_by_visible_text(
            RecordGenerator.random_corresponding_organoid_choice())

        self.driver.find_element(By.ID, "id_sclab_pool").send_keys(
            RecordGenerator.random_string_of_length(5))

        self.driver.find_element(
            By.ID,
            "id_rna_isle_id").send_keys(
                RecordGenerator.random_string_of_length(11))

        self.driver.find_element(
            By.ID,
            "id_atac_isle_id").send_keys(
                RecordGenerator.random_string_of_length(11))

        self.driver.find_element(
            By.ID,
            "id_sclab_comment").send_keys(
                RecordGenerator.random_string_of_length(100))

        self.submit_record()
        self.check_submission()
        self.logout()

    def spatial_input(self):
        self.login("test_Spatial", "test4life")
        self.search_record()

        spatial_method = self.driver.find_element(
            By.ID, "id_spatial_method")
        select_spatial_method = Select(spatial_method)
        select_spatial_method.select_by_visible_text(
            RecordGenerator.random_spatial_method())

        spatial_status = self.driver.find_element(
            By.ID, "id_spatial_status")
        select_spatial_status = Select(spatial_status)
        select_spatial_status.select_by_visible_text(
            RecordGenerator.random_spatial_status())

        self.driver.find_element(By.ID, "id_xenium_run_date").send_keys(
                RecordGenerator.random_date())

        self.driver.find_element(
            By.ID,
            "id_xenium_slide_id").send_keys(
                RecordGenerator.random_string_of_length(10))

        self.driver.find_element(By.ID, "id_xenium_run_id").send_keys(
            RecordGenerator.random_string_of_length(50))

        self.driver.find_element(By.ID, "id_xenium_panel_id").send_keys(
            RecordGenerator.random_string_of_length(50))

        self.driver.find_element(By.ID, "id_merscope_run_date").send_keys(
                RecordGenerator.random_date())

        self.driver.find_element(By.ID, "id_merscope_run_id").send_keys(
            RecordGenerator.random_string_of_length(50))

        self.driver.find_element(By.ID, "id_merscope_panel_id").send_keys(
            RecordGenerator.random_string_of_length(50))

        self.driver.find_element(By.ID, "id_dv_200").send_keys(
            RecordGenerator.random_integer_from_0_to_100())

        self.driver.find_element(By.ID, "id_spatial_comment").send_keys(
            RecordGenerator.random_string_of_length(50))

        self.submit_record()
        self.check_submission()
        self.logout()

    def lb_input(self):
        self.login("test_LB", "test4life")
        self.search_record()

        lb_analyte_type = self.driver.find_element(
            By.ID, "id_lb_analyte_type")
        select_lb_analyte_type = Select(lb_analyte_type)
        select_lb_analyte_type.select_by_visible_text(
            RecordGenerator.random_lb_analyte_types())

        self.driver.find_element(
            By.ID,
            "id_lb_sampling_date").send_keys(
                RecordGenerator.random_date())

        self.driver.find_element(
            By.ID,
            "id_lb_received").send_keys(
                RecordGenerator.random_date())

        self.driver.find_element(By.ID, "id_lb_sample_volume").send_keys(
            RecordGenerator.random_integer_from_0_to_100())

        self.driver.find_element(By.ID, "id_lb_date_of_isolation").send_keys(
                RecordGenerator.random_date())

        self.driver.find_element(
            By.ID,
            "id_lb_total_isolated_cfdna").send_keys(
                RecordGenerator.random_integer_from_0_to_100())

        lb_status = self.driver.find_element(
            By.ID, "id_lb_status")
        select_lb_status = Select(lb_status)
        select_lb_status.select_by_visible_text(
            RecordGenerator.random_lb_status_choice())

        self.submit_record()
        self.check_submission()
        self.logout()

    def omics_input(self):
        self.login("test_Omics", "test4life")
        self.search_record()

        self.driver.find_element(
            By.ID,
            "id_sc_analysis_status").send_keys(
                RecordGenerator.random_scanalysis_choice())

        self.driver.find_element(
            By.ID, "id_scrna_r1").send_keys("omics/schmomociks")

        self.driver.find_element(
            By.ID, "id_scrna_r2").send_keys("omics/schmomociks")

        self.driver.find_element(
            By.ID, "id_scatac_r1").send_keys("omics/schmomociks")

        self.driver.find_element(
            By.ID, "id_scatac_r2").send_keys("omics/schmomociks")

        self.driver.find_element(
            By.ID, "id_scatac_i2").send_keys("omics/schmomociks")

        self.driver.find_element(
            By.ID, "id_wgs_r1").send_keys("omics/schmomociks")

        self.driver.find_element(
            By.ID, "id_wgs_r2").send_keys("omics/schmomociks")

        self.driver.find_element(
            By.ID, "id_wgs_bam").send_keys("omics/schmomociks")

        self.driver.find_element(
            By.ID, "id_wgs_vcf").send_keys("omics/schmomociks")

        self.submit_record()
        self.check_submission()
        self.logout()
