# Generated by Selenium IDE

from selenium.webdriver.common.by import By
from .record_generator import RecordGenerator
from .test_root_create_record_via_form import TestRootCreateRecordViaForm


class TestAllUserGroupsForm(TestRootCreateRecordViaForm):

    def delete_test_record(self):
        self.driver.find_element(By.ID, "all-samples-nav").click()
        self.driver.find_element(By.ID,
                                 f"Delete {self.sat3_sample_code}").click()

    def teardown_method(self, method):

        self.delete_test_record()
        self.logout()
        self.driver.close()
        self.driver.quit()

    def test_all_users_input(self):
        self.recruiter_create()
        self.tum_input()
        self.spl_input()
        self.sclab_input()
        self.lb_input()
        self.omics_input()
        self.login("root", "root")

    def search_record(self):
        self.driver.find_element(
            By.CSS_SELECTOR,
            "#id_radio_select > div:nth-child(2) > label").click()
        self.driver.find_element(
            By.ID, "id_search_field").send_keys(self.sat3_sample_code)
        self.driver.find_element(By.ID, "search-button").click()

    def recruiter_create(self):
        self.login("test_Recruiter", "test4life")
        self.create_minimal_test_record()
        self.submit_record()
        self.check_submission()
        self.logout()

    def tum_input(self):
        self.login("test_TUM", "test4life")
        self.search_record()
        self.driver.find_element(By.ID, "id_tumor_cell_content").send_keys(
            RecordGenerator.random_integer_from_0_to_100())
        self.submit_record()
        self.check_submission()
        self.logout()

    def spl_input(self):
        self.login("test_SPL", "test4life")
        self.search_record()
        self.driver.find_element(
            By.ID,
            "id_spl_received").send_keys(RecordGenerator.random_date())
        spl_status = self.driver.find_element(By.ID, "id_spl_status")
        spl_status.find_element(
            By.XPATH,
            f"//option[. = '{RecordGenerator.random_spl_status()}']").click()
        spl_sequencing_type = self.driver.find_element(
            By.ID,
            "id_spl_sequencing_type")
        spl_sequencing_type.find_element(
            By.XPATH,
            f"//option[. = '{RecordGenerator.random_spl_sequencing()}']"). \
            click()
        self.submit_record()
        self.check_submission()
        self.logout()

    def sclab_input(self):
        self.login("test_ScLab", "test4life")
        self.search_record()
        self.driver.find_element(
            By.ID,
            "id_sclab_received").send_keys(RecordGenerator.random_date())

        self.driver.find_element(
            By.ID,
            "id_sclab_extraction_date").send_keys(
                RecordGenerator.random_date())

        self.driver.find_element(
            By.ID,
            "id_sclab_nuclei_yield").send_keys(
                RecordGenerator.random_integer_from_0_to_100())

        self.driver.find_element(
            By.ID,
            "id_sclab_nuclei_size").send_keys(
                RecordGenerator.random_integer_from_0_to_100())

        sclab_status = self.driver.find_element(By.ID, "id_sclab_status")
        sclab_status.find_element(
            By.XPATH,
            f"//option[. = "
            f"'{RecordGenerator.random_sclab_status_choice()}']").click()

        sclab_sequencing_type = self.driver.find_element(
            By.ID, "id_sclab_sequencing_type")
        sclab_sequencing_type.find_element(
            By.XPATH,
            f"//option[. = "
            f"'{RecordGenerator.random_sclab_sequencing_types()}']").click()

        sclab_sorting = self.driver.find_element(By.ID, "id_sclab_sorting")
        sclab_sorting.find_element(
            By.XPATH,
            f"//option[. = '{RecordGenerator.random_sclab_sorting()}']"). \
            click()

        self.driver.find_element(By.ID, "id_sclab_pool").send_keys(
            RecordGenerator.random_string_of_length(5))

        self.driver.find_element(
            By.ID,
            "id_rna_isle_id").send_keys(
                RecordGenerator.random_integer_from_0_to_100())

        self.driver.find_element(
            By.ID,
            "id_atac_isle_id").send_keys(
                RecordGenerator.random_integer_from_0_to_100())

        self.driver.find_element(
            By.ID,
            "id_sclab_comment").send_keys(
                RecordGenerator.random_string_of_length(100))

        self.submit_record()
        self.check_submission()
        self.logout()

    def lb_input(self):
        self.login("test_LB", "test4life")
        self.search_record()
        lb_analyte_type = self.driver.find_element(By.ID, "id_lb_analyte_type")
        lb_analyte_type.find_element(
            By.XPATH,
            f"//option[. = '{RecordGenerator.random_lb_analyte_types()}']") \
            .click()

        self.driver.find_element(
            By.ID,
            "id_lb_sampling_date").send_keys(
                RecordGenerator.random_date())

        self.driver.find_element(
            By.ID,
            "id_lb_received").send_keys(
                RecordGenerator.random_date())

        self.driver.find_element(By.ID, "id_lb_sample_volume").send_keys(
            RecordGenerator.random_integer_from_0_to_100())

        self.driver.find_element(By.ID, "id_lb_date_of_isolation").send_keys(
                RecordGenerator.random_date())

        self.driver.find_element(
            By.ID,
            "id_lb_total_isolated_cfdna").send_keys(
                RecordGenerator.random_integer_from_0_to_100())

        lb_status = self.driver.find_element(By.ID, "id_lb_status")
        lb_status.find_element(
            By.XPATH,
            f"//option[. = '{RecordGenerator.random_lb_status_choice()}']"). \
            click()

        self.submit_record()
        self.check_submission()
        self.logout()

    def omics_input(self):
        self.login("test_Omics", "test4life")
        self.search_record()
        self.driver.find_element(
            By.ID,
            "id_pools").send_keys(
                RecordGenerator.random_integer_from_0_to_100())

        self.driver.find_element(
            By.ID, "id_scrna_r1").send_keys("omics/schmomociks")

        self.driver.find_element(
            By.ID, "id_scrna_r2").send_keys("omics/schmomociks")

        self.driver.find_element(
            By.ID, "id_scatac_r1").send_keys("omics/schmomociks")

        self.driver.find_element(
            By.ID, "id_scatac_r2").send_keys("omics/schmomociks")

        self.driver.find_element(
            By.ID, "id_scatac_i2").send_keys("omics/schmomociks")

        self.driver.find_element(
            By.ID, "id_wgs_r1").send_keys("omics/schmomociks")

        self.driver.find_element(
            By.ID, "id_wgs_r2").send_keys("omics/schmomociks")

        self.driver.find_element(
            By.ID, "id_wgs_bam").send_keys("omics/schmomociks")

        self.driver.find_element(
            By.ID, "id_wgs_vcf").send_keys("omics/schmomociks")

        self.submit_record()
        self.check_submission()
        self.logout()
