# Generated by Selenium IDE

from selenium.webdriver.common.by import By
from selenium.webdriver.support.select import Select
from backend.gui.selenium.basic_test_functions import BasicTestClass
from .record_generator import RecordGenerator


class TestRootCreateRecordViaForm(BasicTestClass):

    def create_full_record(self):
        """
        Create a complete record as root user.
        """

        self.create_minimal_test_record()

        # TUM

        self.driver.find_element(By.ID, "id_tissue_quality").send_keys(
            RecordGenerator.random_integer_from_1_to_5())

        self.driver.find_element(By.ID, "id_tumor_cell_content").send_keys(
            RecordGenerator.random_integer_from_0_to_100())

        self.driver.find_element(By.ID, "id_percent_avital_cells").send_keys(
            RecordGenerator.random_integer_from_0_to_100())

        self.driver.find_element(By.ID,
                                 "id_comment_tumor_cell_content").send_keys(
            RecordGenerator.random_string_of_length(50))

        # SPL

        self.driver.find_element(
            By.ID,
            "id_spl_received").send_keys(RecordGenerator.random_date())

        spl_status = self.driver.find_element(
            By.ID, "id_spl_status")
        select_spl_status = Select(spl_status)
        select_spl_status.select_by_visible_text(
            RecordGenerator.random_spl_status())

        spl_sequencing_type = self.driver.find_element(
            By.ID, "id_spl_sequencing_type")
        select_spl_sequencing_type = Select(spl_sequencing_type)
        select_spl_sequencing_type.select_by_visible_text(
            RecordGenerator.random_spl_sequencing())

        # ScLab

        self.driver.find_element(
            By.ID,
            "id_sclab_received").send_keys(RecordGenerator.random_date())

        self.driver.find_element(
            By.ID,
            "id_sclab_extraction_date").send_keys(
                RecordGenerator.random_date())

        self.driver.find_element(
            By.ID,
            "id_sclab_nuclei_yield").send_keys(
                RecordGenerator.random_integer_from_0_to_100())

        self.driver.find_element(
            By.ID,
            "id_sclab_nuclei_size").send_keys(
                RecordGenerator.random_integer_from_0_to_100())

        sclab_status = self.driver.find_element(
            By.ID, "id_sclab_status")
        select_sclab_status = Select(sclab_status)
        select_sclab_status.select_by_visible_text(
            RecordGenerator.random_sclab_status_choice())

        sclab_sequencing_type = self.driver.find_element(
            By.ID, "id_sclab_sequencing_type")
        select_sclab_sequencing_type = Select(sclab_sequencing_type)
        select_sclab_sequencing_type.select_by_visible_text(
            RecordGenerator.random_sclab_sequencing_types())

        sclab_sorting = self.driver.find_element(
            By.ID, "id_sclab_sorting")
        select_corresponding_organoid = Select(sclab_sorting)
        select_corresponding_organoid.select_by_visible_text(
            RecordGenerator.random_corresponding_organoid_choice())

        self.driver.find_element(By.ID, "id_sclab_pool").send_keys(
            RecordGenerator.random_string_of_length(5))

        self.driver.find_element(
            By.ID,
            "id_rna_isle_id").send_keys(
                RecordGenerator.random_string_of_length(11))

        self.driver.find_element(
            By.ID,
            "id_atac_isle_id").send_keys(
                RecordGenerator.random_string_of_length(11))

        self.driver.find_element(
            By.ID,
            "id_sclab_comment").send_keys(
                RecordGenerator.random_string_of_length(100))

        # Spatial

        spatial_method = self.driver.find_element(
            By.ID, "id_spatial_method")
        select_spatial_method = Select(spatial_method)
        select_spatial_method.select_by_visible_text(
            RecordGenerator.random_spatial_method())

        spatial_status = self.driver.find_element(
            By.ID, "id_spatial_status")
        select_spatial_status = Select(spatial_status)
        select_spatial_status.select_by_visible_text(
            RecordGenerator.random_spatial_status())

        self.driver.find_element(By.ID, "id_xenium_run_date").send_keys(
                RecordGenerator.random_date())

        self.driver.find_element(
            By.ID,
            "id_xenium_slide_id").send_keys(
                RecordGenerator.random_string_of_length(10))

        self.driver.find_element(By.ID, "id_xenium_run_id").send_keys(
            RecordGenerator.random_string_of_length(50))

        self.driver.find_element(By.ID, "id_xenium_panel_id").send_keys(
            RecordGenerator.random_string_of_length(50))

        self.driver.find_element(By.ID, "id_merscope_run_date").send_keys(
                RecordGenerator.random_date())

        self.driver.find_element(By.ID, "id_merscope_run_id").send_keys(
            RecordGenerator.random_string_of_length(50))

        self.driver.find_element(By.ID, "id_merscope_panel_id").send_keys(
            RecordGenerator.random_string_of_length(50))

        self.driver.find_element(By.ID, "id_dv_200").send_keys(
            RecordGenerator.random_integer_from_0_to_100())

        self.driver.find_element(By.ID, "id_spatial_comment").send_keys(
            RecordGenerator.random_string_of_length(50))

        # LB

        lb_analyte_type = self.driver.find_element(
            By.ID, "id_lb_analyte_type")
        select_lb_analyte_type = Select(lb_analyte_type)
        select_lb_analyte_type.select_by_visible_text(
            RecordGenerator.random_lb_analyte_types())

        self.driver.find_element(
            By.ID,
            "id_lb_panel_r1").send_keys(
                RecordGenerator.random_string_of_length(100))

        self.driver.find_element(
            By.ID,
            "id_lb_panel_r2").send_keys(
                RecordGenerator.random_string_of_length(100))

        lb_sequencing_status = self.driver.find_element(
            By.ID, "id_lb_sequencing_status")
        select_lb_sequencing_status = Select(lb_sequencing_status)
        select_lb_sequencing_status.select_by_visible_text(
            RecordGenerator.random_lb_sequencing_status())

        self.driver.find_element(
            By.ID,
            "id_lb_received").send_keys(
                RecordGenerator.random_date())

        (self.driver.find_element(
            By.ID,
            "id_lb_sample_volume").send_keys(
                RecordGenerator.random_decimal_4_digits_1_decimal()))

        self.driver.find_element(By.ID, "id_lb_date_of_isolation").send_keys(
                RecordGenerator.random_date())

        self.driver.find_element(
            By.ID,
            "id_lb_total_isolated_cfdna").send_keys(
                RecordGenerator.random_integer_from_0_to_100())

        lb_status = self.driver.find_element(
            By.ID, "id_lb_status")
        select_lb_status = Select(lb_status)
        select_lb_status.select_by_visible_text(
            RecordGenerator.random_lb_status_choice())

        # OMICS

        self.driver.find_element(
            By.ID,
            "id_request_execution_of").send_keys(
                RecordGenerator.random_string_of_length(10))

        self.driver.find_element(
            By.ID,
            "id_cell_ranger_arc_run").send_keys(
                RecordGenerator.random_date())

        self.driver.find_element(
            By.ID,
            "id_sc_analysis_status").send_keys(
                RecordGenerator.random_scanalysis_choice())

        self.driver.find_element(
            By.ID, "id_scrna_r1").send_keys("omics/schmomociks")

        self.driver.find_element(
            By.ID, "id_scrna_r2").send_keys("omics/schmomociks")

        self.driver.find_element(
            By.ID, "id_scatac_r1").send_keys("omics/schmomociks")

        self.driver.find_element(
            By.ID, "id_scatac_r2").send_keys("omics/schmomociks")

        self.driver.find_element(
            By.ID, "id_scatac_i2").send_keys("omics/schmomociks")

        self.driver.find_element(
            By.ID, "id_wgs_r1").send_keys("omics/schmomociks")

        self.driver.find_element(
            By.ID, "id_wgs_r2").send_keys("omics/schmomociks")

        self.driver.find_element(
            By.ID, "id_wgs_bam").send_keys("omics/schmomociks")

        self.driver.find_element(
            By.ID, "id_wgs_vcf").send_keys("omics/schmomociks")

    def test_root_create_record_via_form(self):
        self.login("root", "root")
        self.create_full_record()
        self.submit_record()
        self.check_submission()
