# Generated by Django 5.0.1 on 2024-02-05 11:56

import backend.gui.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HistopathologicalSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recruiting_site', models.CharField(choices=[('Essen', 'Essen'), ('Heidelberg', 'Heidelberg'), ('Frankfurt', 'Frankfurt'), ('Göttingen', 'Göttingen'), ('Heidelberg', 'Heidelberg'), ('Köln', 'Köln'), ('München', 'München'), ('Augsburg', 'Augsburg')], max_length=200, verbose_name='Recruiting Site')),
                ('patient_identifier', models.CharField(help_text='5-digit SATURN3 pseudonym               (by Treuhandstelle Freiburg)', max_length=5, validators=[backend.gui.models.validate_alphanumeric], verbose_name='Patient Identifier')),
                ('sex', models.CharField(choices=[('m', 'm'), ('f', 'f')], max_length=200, verbose_name='Sex')),
                ('died', models.DateField(blank=True, null=True, verbose_name='Died')),
                ('saturn3_sample_code', models.CharField(help_text='S3 + Entity -             Patient Identifier -             Sampling Timepoint -             Tissue Type + Order Number -             Storage Format - Analyte Type             + Order Number', max_length=200, verbose_name='SATURN3 Sample Code')),
                ('sampling_date', models.DateField(verbose_name='Sampling Date')),
                ('tissue_type', models.CharField(choices=[('Fresh-Frozen', 'Fresh-Frozen'), ('FFPE', 'FFPE'), ('Viable', 'Viable'), ('Pleurapunctate', 'Pleurapunctate'), ('Ascites', 'Ascites'), ('CTC', 'CTC'), ('PBMC', 'PBMC'), ('Serum', 'Serum'), ('Plasma', 'Plasma'), ('ctDNA', 'ctDNA'), ('Whole blood', 'Whole blood'), ('Organoid', 'Organoid')], max_length=200, verbose_name='Tissue Type')),
                ('type_of_intervention', models.CharField(choices=[('Resection', 'Resection'), ('Biopsy', 'Biopsy'), ('Blood withdrawal', 'Blood withdrawal'), ('Punctate', 'Punctate')], max_length=200, verbose_name='Type of Intervention')),
                ('localisation', models.CharField(choices=[('Pancreas', 'Pancreas'), ('Breast', 'Breast'), ('Colon', 'Colon'), ('Liver', 'Liver'), ('Brain', 'Brain'), ('Lung', 'Lung'), ('Thorax Wall', 'Thorax Wall'), ('Pleura Punctate', 'Pleura Punctate'), ('Ascites', 'Ascites'), ('Blood', 'Blood')], max_length=200, verbose_name='Localisation')),
                ('corresponding_organoid', models.BooleanField(help_text='generated from the same biopsy/tissue piece', verbose_name='Corresponding Organoid')),
                ('grading', models.CharField(choices=[('G1', 'G1'), ('G2', 'G2'), ('G3', 'G3')], max_length=200, verbose_name='Grading')),
                ('tumor_cell_content', models.CharField(blank=True, max_length=200, validators=[backend.gui.models.zero_to_a_hundred], verbose_name='Tumor Cell Content')),
                ('spl_received', models.DateField(blank=True, null=True, verbose_name='SPL Received')),
                ('spl_status', models.CharField(blank=True, choices=[('RNA failed', 'RNA failed'), ('DNA failed', 'DNA failed'), ('sequencing failed', 'sequencing failed'), ('DNA/RNA failed', 'DNA/RNA failed'), ('successful RNA', 'successful RNA'), ('successful DNA', 'successful DNA'), ('successful DNA/RNA', 'successful DNA/RNA')], max_length=200, verbose_name='SPL Status')),
                ('spl_sequencing_type', models.CharField(blank=True, choices=[('panel', 'panel'), ('WGS', 'WGS'), ('WGS/RNA', 'WGS/RNA'), ('WES', 'WES'), ('WES/RNA', 'WES/RNA')], max_length=200, verbose_name='SPL Sequencing Type')),
                ('sclab_received', models.DateField(blank=True, null=True, verbose_name='scLab Received')),
                ('sclab_extraction_date', models.DateField(blank=True, null=True, verbose_name='scLab Extraction Date')),
                ('sclab_nuclei_yield', models.IntegerField(blank=True, null=True, verbose_name='scLab Nuclei Yield')),
                ('sclab_nuclei_size', models.IntegerField(blank=True, null=True, verbose_name='scLab Nuclei Size [µm]')),
                ('sclab_status', models.CharField(blank=True, choices=[('RNA failed', 'RNA failed'), ('DNA failed', 'DNA failed'), ('sequencing failed', 'sequencing failed'), ('DNA/RNA failed', 'DNA/RNA failed'), ('successful RNA', 'successful RNA'), ('successful DNA', 'successful DNA'), ('successful DNA/RNA', 'successful DNA/RNA')], max_length=200, verbose_name='scLab Status')),
                ('sclab_sequencing_type', models.CharField(blank=True, choices=[('Multiome (RNA/ATAC)', 'Multiome (RNA/ATAC)'), ('RNA', 'RNA'), ('DNA', 'DNA'), ('ATAC', 'ATAC')], max_length=200, verbose_name='scLab Sequencing Type')),
                ('sclab_sorting', models.BooleanField(blank=True, null=True, verbose_name='scLab Sorting')),
                ('sclab_pool', models.IntegerField(blank=True, null=True, verbose_name='scLab Pool')),
                ('lb_analyte_type', models.CharField(blank=True, choices=[('Plasma', 'Plasma'), ('CTC', 'CTC'), ('ctDNA', 'ctDNA'), ('PBMC', 'PBMC'), ('Serum', 'Serum')], max_length=200, verbose_name='LB analyte type')),
                ('lb_sampling_date', models.DateField(blank=True, null=True, verbose_name='LB Sampling Date')),
                ('lb_received', models.DateField(blank=True, null=True, verbose_name='LB Received')),
                ('lb_sample_volume', models.IntegerField(blank=True, null=True, verbose_name='LB Sample Volume [ml]')),
                ('lb_date_of_isolation', models.DateField(blank=True, null=True, verbose_name='LB Date of Isolation')),
                ('lb_total_isolated_cfdna', models.IntegerField(blank=True, null=True, verbose_name='LB Total Isolated cfDNA [ng]')),
                ('lb_status', models.CharField(blank=True, choices=[('DNA failed', 'DNA failed'), ('successful DNA', 'successful DNA'), ('sequencing failed', 'sequencing failed'), ('sequencing successful', 'sequencing successful')], max_length=200, verbose_name='LB Status')),
                ('pools', models.CharField(blank=True, max_length=200, null=True, verbose_name='Pools')),
                ('scrna_r1', models.CharField(blank=True, max_length=200, null=True, verbose_name='scRNA R1')),
                ('scrna_r2', models.CharField(blank=True, max_length=200, null=True, verbose_name='scRNA R2')),
                ('scatac_r1', models.CharField(blank=True, max_length=200, null=True, verbose_name='scATAC R1')),
                ('scatac_r2', models.CharField(blank=True, max_length=200, null=True, verbose_name='scATAC R2')),
                ('scatac_i2', models.CharField(blank=True, max_length=200, null=True, verbose_name='scATAC I2')),
                ('wgs_r1', models.CharField(blank=True, max_length=200, null=True, verbose_name='WGS R1')),
                ('wgs_r2', models.CharField(blank=True, max_length=200, null=True, verbose_name='WGS R2')),
                ('wgs_bam', models.CharField(blank=True, max_length=200, null=True, verbose_name='WGS bam')),
                ('wgs_vcf', models.CharField(blank=True, max_length=200, null=True, verbose_name='WGS vcf')),
            ],
        ),
    ]
