# Generated by Django 5.0.1 on 2024-01-25 10:49

import backend.gui.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HistopathologicalSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recruiting_site', models.CharField(choices=[('Essen', 'Essen'), ('Heidelberg', 'Heidelberg'), ('Frankfurt', 'Frankfurt'), ('Göttingen', 'Göttingen'), ('Heidelberg', 'Heidelberg'), ('Köln', 'Köln'), ('München', 'München'), ('Augsburg', 'Augsburg')], max_length=50)),
                ('patient_identifier', models.CharField(help_text='5-digit SATURN3 pseudonym               (by Treuhandstelle Freiburg)', max_length=5, validators=[backend.gui.models.validate_alphanumeric])),
                ('sex', models.CharField(choices=[('d', 'd'), ('f', 'f'), ('m', 'm')], max_length=50)),
                ('died', models.DateField(blank=True, null=True)),
                ('saturn3_sample_code', models.CharField(help_text='S3 + Entity -             Patient Identifier -             Sampling Timepoint -             Tissue Type + Order Number -             Storage Format - Analyte Type             + Order Number', max_length=50, verbose_name='SATURN3 Sample Code')),
                ('sampling_date', models.DateField()),
                ('tissue_type', models.CharField(choices=[('Fresh-Frozen', 'Fresh-Frozen'), ('FFPE', 'FFPE'), ('Viable', 'Viable'), ('Pleurapunctate', 'Pleurapunctate'), ('Ascites', 'Ascites'), ('CTC', 'CTC'), ('PBMC', 'PBMC'), ('Serum', 'Serum'), ('Plasma', 'Plasma'), ('ctDNA', 'ctDNA'), ('Whole blood', 'Whole blood'), ('Organoid', 'Organoid')], max_length=50)),
                ('type_of_intervention', models.CharField(choices=[('Resection', 'Resection'), ('Biopsy', 'Biopsy'), ('Blood withdrawal', 'Blood withdrawal'), ('Punctate', 'Punctate')], max_length=50)),
                ('localisation', models.CharField(choices=[('Pancreas', 'Pancreas'), ('Breast', 'Breast'), ('Colon', 'Colon'), ('Liver', 'Liver'), ('Brain', 'Brain'), ('Lung', 'Lung'), ('Thorax Wall', 'Thorax Wall'), ('Pleura Punctate', 'Pleura Punctate'), ('Ascites', 'Ascites'), ('Blood', 'Blood')], max_length=50)),
                ('corresponding_organoid', models.BooleanField(help_text='generated from the same biopsy/tissue piece')),
                ('grading', models.CharField(choices=[('G1', 'G1'), ('G2', 'G2'), ('G3', 'G3')], max_length=50)),
                ('tumor_cell_content', models.CharField(blank=True, max_length=50, validators=[backend.gui.models.zero_to_a_hundred])),
                ('spl_received', models.DateField(blank=True, null=True, verbose_name='SPL received')),
                ('spl_status', models.CharField(blank=True, choices=[('RNA failed', 'RNA failed'), ('DNA failed', 'DNA failed'), ('sequencing failed', 'sequencing failed'), ('DNA/RNA failed', 'DNA/RNA failed'), ('successful RNA', 'successful RNA'), ('successful DNA', 'successful DNA'), ('successful DNA/RNA', 'successful DNA/RNA')], max_length=50, verbose_name='SPL status')),
                ('spl_sequencing_type', models.CharField(blank=True, choices=[('panel', 'panel'), ('WGS', 'WGS'), ('WGS/RNA', 'WGS/RNA'), ('WES', 'WES'), ('WES/RNA', 'WES/RNA')], max_length=50, verbose_name='SPL sequencing type')),
                ('sclab_received', models.DateField(blank=True, null=True, verbose_name='scLab received')),
                ('sclab_extraction_date', models.DateField(blank=True, null=True, verbose_name='scLab                                                 extraction date')),
                ('sclab_nuclei_yield', models.IntegerField(blank=True, null=True, verbose_name='scLab nuclei yield')),
                ('sclab_nuclei_size', models.IntegerField(blank=True, null=True, verbose_name='scLab nuclei                                                  size [µm]')),
                ('sclab_status', models.CharField(blank=True, max_length=50, verbose_name='scLab status')),
                ('sclac_sequencing_type', models.CharField(blank=True, max_length=50, verbose_name='scLab                                                  sequencing type')),
                ('sclab_sorting', models.BooleanField(blank=True, null=True, verbose_name='scLab sorting')),
                ('sclab_pool', models.IntegerField(blank=True, null=True, verbose_name='scLab pool')),
                ('lb_analyte_type', models.CharField(blank=True, choices=[('Plasma', 'Plasma'), ('CTC', 'CTC'), ('ctDNA', 'ctDNA'), ('PBMC', 'PBMC'), ('Serum', 'Serum')], max_length=50, verbose_name='LB analyte type')),
                ('lb_sampling_date', models.DateField(blank=True, null=True, verbose_name='LB sampling date')),
                ('lb_received', models.DateField(blank=True, null=True, verbose_name='LB received')),
                ('lb_sample_volume', models.IntegerField(blank=True, null=True, verbose_name='LB sample                                              volume [ml]')),
                ('lb_date_of_isolation', models.DateField(blank=True, null=True, verbose_name='LB date                                                  of isolation')),
                ('lb_total_isolated_cfdna', models.IntegerField(blank=True, null=True, verbose_name='LB total                                                      isolated cfDNA [ng]')),
                ('lb_status', models.CharField(blank=True, choices=[('DNA failed', 'DNA failed'), ('successful DNA', 'successful DNA'), ('sequencing failed', 'sequencing failed'), ('sequencing successful', 'sequencing successful')], max_length=50, verbose_name='LB status')),
            ],
        ),
    ]
