# Generated by Django 4.2.5 on 2024-01-09 13:22

import backend.gui.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HistopathologicalSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recruiting_site', models.CharField(choices=[('Freiburg', 'Freiburg'), ('Essen', 'Essen'), ('Heidelberg', 'Heidelberg'), ('Frankfurt', 'Frankfurt'), ('Göttingen', 'Göttingen'), ('Heidelberg', 'Heidelberg'), ('Köln', 'Köln'), ('München', 'München'), ('Augsburg', 'Augsburg')], max_length=50)),
                ('patient_identifier', models.CharField(help_text='5-digit SATURN3 pseudonym (by Treuhandstelle Freiburg)', max_length=5, validators=[backend.gui.models.validate_alphanumeric])),
                ('died', models.DateField(blank=True, null=True)),
                ('SATURN3 Sample Code', models.CharField(help_text='S3+Entity - Patient Identifier - Sampling Timepoint - Tissue Type + Order Number - Storage Format - Analyte Type + Order Number', max_length=50)),
                ('sampling_date', models.DateField()),
                ('tissue_type', models.CharField(choices=[('Fresh-Frozen', 'Fresh-Frozen'), ('FFPE', 'FFPE'), ('Viable', 'Viable'), ('Pleurapunctate', 'Pleurapunctate'), ('Ascites', 'Ascites'), ('CTC', 'CTC'), ('PBMC', 'PBMC'), ('Serum', 'Serum'), ('Plasma', 'Plasma'), ('ctDNA', 'ctDNA'), ('Whole blood', 'Whole blood'), ('Organoid', 'Organoid')], max_length=50)),
                ('type_of_intervention', models.CharField(choices=[('Resection', 'Resection'), ('Biopsy', 'Biopsy'), ('Blood withdrawal', 'Blood withdrawal'), ('Punctate', 'Punctate')], max_length=50)),
                ('localisation', models.CharField(choices=[('Pancreas', 'Pancreas'), ('Breast', 'Breast'), ('Colon', 'Colon'), ('Liver', 'Liver'), ('Brain', 'Brain'), ('Lung', 'Lung'), ('Thorax wall', 'Thorax wall'), ('Pleura Punctate', 'Pleura Punctate'), ('Ascites', 'Ascites'), ('Blood', 'Blood')], max_length=50)),
                ('corresponding_organoid', models.BooleanField(help_text='generated from the same biopsy/tissue piece')),
                ('grading', models.CharField(choices=[('G1', 'G1'), ('G2', 'G2'), ('G3', 'G3')], max_length=50)),
                ('tumor_cell_content', models.CharField(blank=True, max_length=50, validators=[backend.gui.models.zero_to_a_hundred])),
                ('spl_received', models.DateField(blank=True, null=True, verbose_name='SPL received')),
                ('SPL status', models.CharField(blank=True, choices=[('RNA failed', 'RNA failed'), ('DNA failed', 'DNA failed'), ('sequencing failed', 'sequencing failed'), ('DNA/RNA failed', 'DNA/RNA failed'), ('successful RNA', 'successful RNA'), ('successful DNA', 'successful DNA'), ('successful DNA/RNA', 'successful DNA/RNA')], max_length=50)),
                ('SPL sequencing type', models.CharField(blank=True, choices=[('panel', 'panel'), ('WGS', 'WGS'), ('WGS/RNA', 'WGS/RNA'), ('WES', 'WES'), ('WES/RNA', 'WES/RNA')], max_length=50)),
                ('sclab_received', models.DateField(blank=True, null=True, verbose_name='scLab received')),
                ('sclab_extraction_date', models.DateField(blank=True, null=True, verbose_name='scLab extraction date')),
                ('scLab nuclei yield', models.IntegerField(blank=True, null=True)),
                ('scLab nuclei size [µm]', models.IntegerField(blank=True, null=True)),
                ('scLab status', models.CharField(blank=True, max_length=50)),
                ('scLab sequencing type', models.CharField(blank=True, max_length=50)),
                ('scLab sorting', models.BooleanField(blank=True, null=True)),
                ('scLab pool', models.IntegerField(blank=True, null=True)),
                ('LB analyte type', models.CharField(blank=True, choices=[('Plasma', 'Plasma'), ('CTC', 'CTC'), ('ctDNA', 'ctDNA'), ('PBMC', 'PBMC'), ('Serum', 'Serum')], max_length=50)),
                ('lb_sampling_date', models.DateField(blank=True, null=True, verbose_name='LB sampling date')),
                ('lb_received', models.DateField(blank=True, null=True, verbose_name='LB received')),
                ('LB sample volume [ml]', models.IntegerField(blank=True, null=True)),
                ('lb_date_of_isolation', models.DateField(blank=True, null=True, verbose_name='LB date of isolation')),
                ('LB total isolated cfDNA [ng]', models.IntegerField(blank=True, null=True)),
                ('LB status', models.CharField(blank=True, choices=[('DNA failed', 'DNA failed'), ('successful DNA', 'successful DNA'), ('sequencing failed', 'sequencing failed'), ('sequencing successful', 'sequencing successful')], max_length=50)),
            ],
        ),
    ]
