# Generated by Django 5.0.1 on 2024-02-23 13:44

from django.db import migrations
from django.contrib.auth.models import Group


def generate_groups(apps, schema_editor):
    Group.objects.get_or_create(name="admins")
    Group.objects.get_or_create(name="coordinators")
    Group.objects.get_or_create(name="LiquidBiopsy")
    Group.objects.get_or_create(name="scOpenLab")
    Group.objects.get_or_create(name="SPL")
    Group.objects.get_or_create(name="TUM")
    Group.objects.get_or_create(name="Recruiter")
    Group.objects.get_or_create(name="OmicsPath")
    Group.objects.get_or_create(name="Spatial")


class Migration(migrations.Migration):

    dependencies = [
        ('gui', '0001_initial'),
    ]

    operations = [  
        migrations.RunPython(generate_groups)
    ]
