# Generated by Django 5.0.1 on 2024-02-16 09:51

import backend.gui.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gui', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='histopathologicalsample',
            name='grading',
            field=models.CharField(blank=True, choices=[('G1', 'G1'), ('G2', 'G2'), ('G3', 'G3')], max_length=200, verbose_name='Grading'),
        ),
        migrations.AlterField(
            model_name='histopathologicalsample',
            name='recruiting_site',
            field=models.CharField(choices=[('Essen', 'Essen'), ('Heidelberg', 'Heidelberg'), ('Frankfurt', 'Frankfurt'), ('Göttingen', 'Göttingen'), ('Köln', 'Köln'), ('München', 'München'), ('Augsburg', 'Augsburg')], max_length=200, verbose_name='Recruiting Site'),
        ),
        migrations.AlterField(
            model_name='histopathologicalsample',
            name='saturn3_sample_code',
            field=models.CharField(help_text='S3 + Entity - Patient Identifier - Sampling Timepoint - Tissue Type + Order Number - Storage Format - Analyte Type + Order Number', max_length=200, validators=[backend.gui.models.check_sat3_sample_code], verbose_name='SATURN3 Sample Code'),
        ),
    ]
