# Generated by Django 5.0.1 on 2024-01-26 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gui', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='histopathologicalsample',
            name='sex',
            field=models.CharField(choices=[('d', 'd'), ('m', 'm'), ('f', 'f')], max_length=50),
        ),
    ]
