# Generated by Django 5.0.1 on 2024-02-15 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gui', '0002_alter_histopathologicalsample_saturn3_sample_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='histopathologicalsample',
            name='grading',
            field=models.CharField(blank=True, choices=[('G1', 'G1'), ('G2', 'G2'), ('G3', 'G3')], max_length=200, verbose_name='Grading'),
        ),
    ]
