# Generated by Django 5.0.1 on 2024-01-26 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gui', '0003_alter_histopathologicalsample_sex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='histopathologicalsample',
            name='sex',
            field=models.CharField(choices=[('f', 'f'), ('m', 'm')], max_length=50),
        ),
    ]
