# Generated by Django 5.0.1 on 2024-03-28 14:04

import backend.gui.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gui', '0003_alter_histopathologicalsample_saturn3_sample_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='histopathologicalsample',
            name='atac_isle_id',
            field=models.CharField(blank=True, max_length=6, null=True, validators=[backend.gui.models.check_six_figures], verbose_name='ATAC Isle ID'),
        ),
        migrations.AddField(
            model_name='histopathologicalsample',
            name='rna_isle_id',
            field=models.CharField(blank=True, max_length=6, null=True, validators=[backend.gui.models.check_six_figures], verbose_name='RNA Isle ID'),
        ),
        migrations.AddField(
            model_name='histopathologicalsample',
            name='sclab_comment',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='scLab Comment'),
        ),
        migrations.AlterField(
            model_name='histopathologicalsample',
            name='pools',
            field=models.CharField(blank=True, null=True, verbose_name='Pools'),
        ),
        migrations.AlterField(
            model_name='histopathologicalsample',
            name='scatac_i2',
            field=models.CharField(blank=True, null=True, verbose_name='scATAC I2'),
        ),
        migrations.AlterField(
            model_name='histopathologicalsample',
            name='scatac_r1',
            field=models.CharField(blank=True, null=True, verbose_name='scATAC R1'),
        ),
        migrations.AlterField(
            model_name='histopathologicalsample',
            name='scatac_r2',
            field=models.CharField(blank=True, null=True, verbose_name='scATAC R2'),
        ),
        migrations.AlterField(
            model_name='histopathologicalsample',
            name='sclab_pool',
            field=models.CharField(blank=True, null=True, verbose_name='scLab Pool'),
        ),
        migrations.AlterField(
            model_name='histopathologicalsample',
            name='sclab_sequencing_type',
            field=models.CharField(blank=True, choices=[('Multiome (RNA/ATAC)', 'Multiome (RNA/ATAC)'), ('RNA', 'RNA'), ('ATAC', 'ATAC')], max_length=200, null=True, verbose_name='scLab Sequencing Type'),
        ),
        migrations.AlterField(
            model_name='histopathologicalsample',
            name='sclab_status',
            field=models.CharField(blank=True, choices=[('RNA failed', 'RNA failed'), ('ATAC failed', 'ATAC failed'), ('sequencing failed', 'sequencing failed'), ('ATAC/RNA failed', 'ATAC/RNA failed'), ('successful RNA', 'successful RNA'), ('successful ATAC', 'successful ATAC'), ('successful ATAC/RNA', 'successful ATAC/RNA')], max_length=200, null=True, verbose_name='scLab Status'),
        ),
        migrations.AlterField(
            model_name='histopathologicalsample',
            name='scrna_r1',
            field=models.CharField(blank=True, null=True, verbose_name='scRNA R1'),
        ),
        migrations.AlterField(
            model_name='histopathologicalsample',
            name='scrna_r2',
            field=models.CharField(blank=True, null=True, verbose_name='scRNA R2'),
        ),
        migrations.AlterField(
            model_name='histopathologicalsample',
            name='wgs_bam',
            field=models.CharField(blank=True, null=True, verbose_name='WGS bam'),
        ),
        migrations.AlterField(
            model_name='histopathologicalsample',
            name='wgs_r1',
            field=models.CharField(blank=True, null=True, verbose_name='WGS R1'),
        ),
        migrations.AlterField(
            model_name='histopathologicalsample',
            name='wgs_r2',
            field=models.CharField(blank=True, null=True, verbose_name='WGS R2'),
        ),
        migrations.AlterField(
            model_name='histopathologicalsample',
            name='wgs_vcf',
            field=models.CharField(blank=True, null=True, verbose_name='WGS vcf'),
        ),
    ]
