# Generated by Django 5.0.1 on 2024-01-26 12:59

import backend.gui.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gui', '0004_alter_histopathologicalsample_sex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='histopathologicalsample',
            name='corresponding_organoid',
            field=models.BooleanField(help_text='generated from the same biopsy/tissue piece', verbose_name='Corresponding Organoid'),
        ),
        migrations.AlterField(
            model_name='histopathologicalsample',
            name='died',
            field=models.DateField(blank=True, null=True, verbose_name='Died'),
        ),
        migrations.AlterField(
            model_name='histopathologicalsample',
            name='grading',
            field=models.CharField(choices=[('G1', 'G1'), ('G2', 'G2'), ('G3', 'G3')], max_length=50, verbose_name='Grading'),
        ),
        migrations.AlterField(
            model_name='histopathologicalsample',
            name='lb_date_of_isolation',
            field=models.DateField(blank=True, null=True, verbose_name='LB Date of Isolation'),
        ),
        migrations.AlterField(
            model_name='histopathologicalsample',
            name='lb_received',
            field=models.DateField(blank=True, null=True, verbose_name='LB Received'),
        ),
        migrations.AlterField(
            model_name='histopathologicalsample',
            name='lb_sample_volume',
            field=models.IntegerField(blank=True, null=True, verbose_name='LB Sample Volume [ml]'),
        ),
        migrations.AlterField(
            model_name='histopathologicalsample',
            name='lb_sampling_date',
            field=models.DateField(blank=True, null=True, verbose_name='LB Sampling Date'),
        ),
        migrations.AlterField(
            model_name='histopathologicalsample',
            name='lb_status',
            field=models.CharField(blank=True, choices=[('DNA failed', 'DNA failed'), ('successful DNA', 'successful DNA'), ('sequencing failed', 'sequencing failed'), ('sequencing successful', 'sequencing successful')], max_length=50, verbose_name='LB Status'),
        ),
        migrations.AlterField(
            model_name='histopathologicalsample',
            name='lb_total_isolated_cfdna',
            field=models.IntegerField(blank=True, null=True, verbose_name='LB Total Isolated cfDNA [ng]'),
        ),
        migrations.AlterField(
            model_name='histopathologicalsample',
            name='localisation',
            field=models.CharField(choices=[('Pancreas', 'Pancreas'), ('Breast', 'Breast'), ('Colon', 'Colon'), ('Liver', 'Liver'), ('Brain', 'Brain'), ('Lung', 'Lung'), ('Thorax Wall', 'Thorax Wall'), ('Pleura Punctate', 'Pleura Punctate'), ('Ascites', 'Ascites'), ('Blood', 'Blood')], max_length=50, verbose_name='Localisation'),
        ),
        migrations.AlterField(
            model_name='histopathologicalsample',
            name='patient_identifier',
            field=models.CharField(help_text='5-digit SATURN3 pseudonym               (by Treuhandstelle Freiburg)', max_length=5, validators=[backend.gui.models.validate_alphanumeric], verbose_name='Patient Identifier'),
        ),
        migrations.AlterField(
            model_name='histopathologicalsample',
            name='recruiting_site',
            field=models.CharField(choices=[('Essen', 'Essen'), ('Heidelberg', 'Heidelberg'), ('Frankfurt', 'Frankfurt'), ('Göttingen', 'Göttingen'), ('Heidelberg', 'Heidelberg'), ('Köln', 'Köln'), ('München', 'München'), ('Augsburg', 'Augsburg')], max_length=50, verbose_name='Recruiting Site'),
        ),
        migrations.AlterField(
            model_name='histopathologicalsample',
            name='sampling_date',
            field=models.DateField(verbose_name='Sampling Date'),
        ),
        migrations.AlterField(
            model_name='histopathologicalsample',
            name='sclab_extraction_date',
            field=models.DateField(blank=True, null=True, verbose_name='scLab Extraction Date'),
        ),
        migrations.AlterField(
            model_name='histopathologicalsample',
            name='sclab_nuclei_size',
            field=models.IntegerField(blank=True, null=True, verbose_name='scLab Nuclei Size [µm]'),
        ),
        migrations.AlterField(
            model_name='histopathologicalsample',
            name='sclab_nuclei_yield',
            field=models.IntegerField(blank=True, null=True, verbose_name='scLab Nuclei Yield'),
        ),
        migrations.AlterField(
            model_name='histopathologicalsample',
            name='sclab_pool',
            field=models.IntegerField(blank=True, null=True, verbose_name='scLab Pool'),
        ),
        migrations.AlterField(
            model_name='histopathologicalsample',
            name='sclab_received',
            field=models.DateField(blank=True, null=True, verbose_name='scLab Received'),
        ),
        migrations.AlterField(
            model_name='histopathologicalsample',
            name='sclab_sequencing_type',
            field=models.CharField(blank=True, choices=[('Multiome (RNA/ATAC)', 'Multiome (RNA/ATAC)'), ('RNA', 'RNA'), ('DNA', 'DNA'), ('ATAC', 'ATAC')], max_length=50, verbose_name='scLab Sequencing Type'),
        ),
        migrations.AlterField(
            model_name='histopathologicalsample',
            name='sclab_sorting',
            field=models.BooleanField(blank=True, null=True, verbose_name='scLab Sorting'),
        ),
        migrations.AlterField(
            model_name='histopathologicalsample',
            name='sclab_status',
            field=models.CharField(blank=True, choices=[('RNA failed', 'RNA failed'), ('DNA failed', 'DNA failed'), ('sequencing failed', 'sequencing failed'), ('DNA/RNA failed', 'DNA/RNA failed'), ('successful RNA', 'successful RNA'), ('successful DNA', 'successful DNA'), ('successful DNA/RNA', 'successful DNA/RNA')], max_length=50, verbose_name='scLab Status'),
        ),
        migrations.AlterField(
            model_name='histopathologicalsample',
            name='sex',
            field=models.CharField(choices=[('f', 'f'), ('m', 'm')], max_length=50, verbose_name='Sex'),
        ),
        migrations.AlterField(
            model_name='histopathologicalsample',
            name='spl_received',
            field=models.DateField(blank=True, null=True, verbose_name='SPL Received'),
        ),
        migrations.AlterField(
            model_name='histopathologicalsample',
            name='spl_sequencing_type',
            field=models.CharField(blank=True, choices=[('panel', 'panel'), ('WGS', 'WGS'), ('WGS/RNA', 'WGS/RNA'), ('WES', 'WES'), ('WES/RNA', 'WES/RNA')], max_length=50, verbose_name='SPL Sequencing Type'),
        ),
        migrations.AlterField(
            model_name='histopathologicalsample',
            name='spl_status',
            field=models.CharField(blank=True, choices=[('RNA failed', 'RNA failed'), ('DNA failed', 'DNA failed'), ('sequencing failed', 'sequencing failed'), ('DNA/RNA failed', 'DNA/RNA failed'), ('successful RNA', 'successful RNA'), ('successful DNA', 'successful DNA'), ('successful DNA/RNA', 'successful DNA/RNA')], max_length=50, verbose_name='SPL Status'),
        ),
        migrations.AlterField(
            model_name='histopathologicalsample',
            name='tissue_type',
            field=models.CharField(choices=[('Fresh-Frozen', 'Fresh-Frozen'), ('FFPE', 'FFPE'), ('Viable', 'Viable'), ('Pleurapunctate', 'Pleurapunctate'), ('Ascites', 'Ascites'), ('CTC', 'CTC'), ('PBMC', 'PBMC'), ('Serum', 'Serum'), ('Plasma', 'Plasma'), ('ctDNA', 'ctDNA'), ('Whole blood', 'Whole blood'), ('Organoid', 'Organoid')], max_length=50, verbose_name='Tissue Type'),
        ),
        migrations.AlterField(
            model_name='histopathologicalsample',
            name='tumor_cell_content',
            field=models.CharField(blank=True, max_length=50, validators=[backend.gui.models.zero_to_a_hundred], verbose_name='Tumor Cell Content'),
        ),
        migrations.AlterField(
            model_name='histopathologicalsample',
            name='type_of_intervention',
            field=models.CharField(choices=[('Resection', 'Resection'), ('Biopsy', 'Biopsy'), ('Blood withdrawal', 'Blood withdrawal'), ('Punctate', 'Punctate')], max_length=50, verbose_name='Type of Intervention'),
        ),
    ]
