# Generated by Django 5.0.1 on 2024-01-26 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gui', '0005_alter_histopathologicalsample_corresponding_organoid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='histopathologicalsample',
            name='pools',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Pools'),
        ),
        migrations.AddField(
            model_name='histopathologicalsample',
            name='scrna_r1',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='scRNA R1'),
        ),
    ]
