# Generated by Django 5.0.1 on 2024-01-26 14:00

import backend.gui.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gui', '0006_histopathologicalsample_pools_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='histopathologicalsample',
            name='grading',
            field=models.CharField(choices=[('G1', 'G1'), ('G2', 'G2'), ('G3', 'G3')], max_length=200, verbose_name='Grading'),
        ),
        migrations.AlterField(
            model_name='histopathologicalsample',
            name='lb_analyte_type',
            field=models.CharField(blank=True, choices=[('Plasma', 'Plasma'), ('CTC', 'CTC'), ('ctDNA', 'ctDNA'), ('PBMC', 'PBMC'), ('Serum', 'Serum')], max_length=200, verbose_name='LB analyte type'),
        ),
        migrations.AlterField(
            model_name='histopathologicalsample',
            name='lb_status',
            field=models.CharField(blank=True, choices=[('DNA failed', 'DNA failed'), ('successful DNA', 'successful DNA'), ('sequencing failed', 'sequencing failed'), ('sequencing successful', 'sequencing successful')], max_length=200, verbose_name='LB Status'),
        ),
        migrations.AlterField(
            model_name='histopathologicalsample',
            name='localisation',
            field=models.CharField(choices=[('Pancreas', 'Pancreas'), ('Breast', 'Breast'), ('Colon', 'Colon'), ('Liver', 'Liver'), ('Brain', 'Brain'), ('Lung', 'Lung'), ('Thorax Wall', 'Thorax Wall'), ('Pleura Punctate', 'Pleura Punctate'), ('Ascites', 'Ascites'), ('Blood', 'Blood')], max_length=200, verbose_name='Localisation'),
        ),
        migrations.AlterField(
            model_name='histopathologicalsample',
            name='pools',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Pools'),
        ),
        migrations.AlterField(
            model_name='histopathologicalsample',
            name='recruiting_site',
            field=models.CharField(choices=[('Essen', 'Essen'), ('Heidelberg', 'Heidelberg'), ('Frankfurt', 'Frankfurt'), ('Göttingen', 'Göttingen'), ('Heidelberg', 'Heidelberg'), ('Köln', 'Köln'), ('München', 'München'), ('Augsburg', 'Augsburg')], max_length=200, verbose_name='Recruiting Site'),
        ),
        migrations.AlterField(
            model_name='histopathologicalsample',
            name='saturn3_sample_code',
            field=models.CharField(help_text='S3 + Entity -             Patient Identifier -             Sampling Timepoint -             Tissue Type + Order Number -             Storage Format - Analyte Type             + Order Number', max_length=200, verbose_name='SATURN3 Sample Code'),
        ),
        migrations.AlterField(
            model_name='histopathologicalsample',
            name='sclab_sequencing_type',
            field=models.CharField(blank=True, choices=[('Multiome (RNA/ATAC)', 'Multiome (RNA/ATAC)'), ('RNA', 'RNA'), ('DNA', 'DNA'), ('ATAC', 'ATAC')], max_length=200, verbose_name='scLab Sequencing Type'),
        ),
        migrations.AlterField(
            model_name='histopathologicalsample',
            name='sclab_status',
            field=models.CharField(blank=True, choices=[('RNA failed', 'RNA failed'), ('DNA failed', 'DNA failed'), ('sequencing failed', 'sequencing failed'), ('DNA/RNA failed', 'DNA/RNA failed'), ('successful RNA', 'successful RNA'), ('successful DNA', 'successful DNA'), ('successful DNA/RNA', 'successful DNA/RNA')], max_length=200, verbose_name='scLab Status'),
        ),
        migrations.AlterField(
            model_name='histopathologicalsample',
            name='scrna_r1',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='scRNA R1'),
        ),
        migrations.AlterField(
            model_name='histopathologicalsample',
            name='sex',
            field=models.CharField(choices=[('m', 'm'), ('f', 'f')], max_length=200, verbose_name='Sex'),
        ),
        migrations.AlterField(
            model_name='histopathologicalsample',
            name='spl_sequencing_type',
            field=models.CharField(blank=True, choices=[('panel', 'panel'), ('WGS', 'WGS'), ('WGS/RNA', 'WGS/RNA'), ('WES', 'WES'), ('WES/RNA', 'WES/RNA')], max_length=200, verbose_name='SPL Sequencing Type'),
        ),
        migrations.AlterField(
            model_name='histopathologicalsample',
            name='spl_status',
            field=models.CharField(blank=True, choices=[('RNA failed', 'RNA failed'), ('DNA failed', 'DNA failed'), ('sequencing failed', 'sequencing failed'), ('DNA/RNA failed', 'DNA/RNA failed'), ('successful RNA', 'successful RNA'), ('successful DNA', 'successful DNA'), ('successful DNA/RNA', 'successful DNA/RNA')], max_length=200, verbose_name='SPL Status'),
        ),
        migrations.AlterField(
            model_name='histopathologicalsample',
            name='tissue_type',
            field=models.CharField(choices=[('Fresh-Frozen', 'Fresh-Frozen'), ('FFPE', 'FFPE'), ('Viable', 'Viable'), ('Pleurapunctate', 'Pleurapunctate'), ('Ascites', 'Ascites'), ('CTC', 'CTC'), ('PBMC', 'PBMC'), ('Serum', 'Serum'), ('Plasma', 'Plasma'), ('ctDNA', 'ctDNA'), ('Whole blood', 'Whole blood'), ('Organoid', 'Organoid')], max_length=200, verbose_name='Tissue Type'),
        ),
        migrations.AlterField(
            model_name='histopathologicalsample',
            name='tumor_cell_content',
            field=models.CharField(blank=True, max_length=200, validators=[backend.gui.models.zero_to_a_hundred], verbose_name='Tumor Cell Content'),
        ),
        migrations.AlterField(
            model_name='histopathologicalsample',
            name='type_of_intervention',
            field=models.CharField(choices=[('Resection', 'Resection'), ('Biopsy', 'Biopsy'), ('Blood withdrawal', 'Blood withdrawal'), ('Punctate', 'Punctate')], max_length=200, verbose_name='Type of Intervention'),
        ),
    ]
